### ISSUE TITLE
Unable to use check_rabbitmq_cluster

### ISSUE THREAD

**Issue by eLvErDe** [nagios-plugins-rabbitmq/nagios-plugins-rabbitmq#78]
Hello,

I must be dump or something but I cannot figure a way to get check_rabbitmq_cluster actually check for the active nodes.

It keeps saying stuff like this:

```
root@centreon:~# /usr/lib/nagios/plugins/check_rabbitmq_cluster -H luigi.domain --username='monitoring' --password='password' -c 3,3,-1
RABBITMQ_CLUSTER OK - nb_running_node OK (2) nb_running_disc_node OK (2) nb_running_ram_node OK (0)
```

When looking a the --help I expect the script to return critical if nb_running_node < 3 or nb_running_disc_node < 3 which is exacly what's going on there but it says ok.

Same occurs with --nodes="rabbit@node1.domain,rabbit@node2.domain". When doing this it keeps returning critical state...

Thanks,

Adam.

**Comment by barryib** [comment]
@eLvErDe I think that the threshold you're using is not the right one for
what you want.

-c 3,3,-1 means alert if nodes number is <0 and >3.

What you want is probably something like this: -c 3:,3:,-1.

See the nagios plugin threshold format for more details
https://nagios-plugins.org/doc/guidelines.html#THRESHOLDFORMAT

Can you please tell me if that helps? If yes, can you please close the
issue?

Cheers,
Thierno

Le mar. 24 janv. 2017 à 20:46, Adam Cécile <notifications@github.com> a
écrit :

**Comment by barryib** [comment]
@eLvErDe I think that the threshold you're using is not the right one for
what you want.

`-c 3,3,-1` means alert if nodes number is <0 and >3.

What you want is probably something like this: `-c 3:,3:,-1`

See the nagios plugin threshold format for more details
https://nagios-plugins.org/doc/guidelines.html#THRESHOLDFORMAT

Can you please tell me if that helps? If yes, can you please close the
issue?

Cheers,
Thierno

**Comment by eLvErDe** [comment]
Hello,

Yes indeed, it seems to work when adding semicolon. To be honest, I'm 
using several nagios-like instances with thousands of services and it's 
the first time I had to ask github for help regarding a script.
What you think about adding an example with minimal count (which is 
basically what people want to do) in the --help, as well as a link to 
the document below regarding thresholds ?

Best regards, Adam.

**Comment by barryib** [comment]
@eLvErDe Right, I understood your point.

I started working on improving scripts documentation, but I don't finish it
because of lack of time
https://github.com/nagios-plugins-rabbitmq/nagios-plugins-rabbitmq/blob/update-pod-documenations/scripts/check_rabbitmq_cluster#L315

But so far, I only reference the nagios documentation for threshold format.

Do you think that is ok? Any other suggestions?

Don't hesitate to submit PR, they very welcomed.

PS: I'm going to work on this only in march.
-- 

---
Thierno IB. BARRY / IT Ninja

[image: Twitter]  <https://twitter.com/barryib>[image: LinkedIn]
<https://fr.linkedin.com/in/barryib>[image: Github]
<https://github.com/barryib>

**Comment by barryib** [comment]
closing this.

Doc will be improved by #70  and #81
